version: "3"

services:
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile

    image: tebahsoft/kounipunc-backend
    ports:
      - 8080:8080

    
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile

    image: tebahsoft/kounipunc-frontend
    ports:
      - 8501:80
